apiVersion: tekton.dev/v1beta1
kind: task
metadata:
  name: onboard-user
spec:
  params:
    - name: NAMESPAPCE
      type: string
    - name: CLUSTER
      type: string
    - name: DESCRIPTION
      type: string
    - name: USERS
      type: string
    - name: QUOTA
      type: string
    - name: GPGKey
      type: string
  steps:
    - name: clone-config-repo
      script:

        echo "Cloning configuration repo..."
        # Clone repository
        git clone *Repo address*
        cd repo

    - name: create-data-file
      script:
        
        echo -e "namespace: $(params.NAMESPACE)\ngroup: $(params.GROUP)\nquota: $(params.QUOTA)\ncluster: $(params.CLUSTER)" > data.yaml
        
        cat > data.yaml << 'EOF'
        namespace: $(params.NAMESPACE)
        group: $(params.GROUP)
        quota: $(params.QUOTA)
        cluster: $(params.CLUSTER)
        EOF

    - name: create-patch
      script:
      
        mustache ~/data.yaml ~/onboarding.template.patch > ~/onboarding.patch

    - name: apply-and-submit-PR
      script:
        git checkout -b "onboarding/$(params.NAMESPACE)"
        git apply ~/onboarding.patch
        git add ./cluster-scope/base/core/namespaces/$(params.NAMESPACE)/kustomization.yaml
        git add ./cluster-scope/base/core/namespaces/$(params.NAMESPACE)/namespace.yaml
        git add ./cluster-scope/overlays/prod/$(params.CLUSTER)/kustomization.yaml
        git commit -m "onboarding $(params.NAMESPACE)"
        git push -u origin HEAD
        gh pr create -R *REPO NAME* --title "Onboardng $(params.NAMESPACE)" --body "$(params.DESCRIPTION) GPG Key - $(params.GPGKey)" -f
