apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: issue-form-automation-bash
spec:
  params:
    - name: SOURCE_REPO
    - name: TARGET_REPO
    - name: ISSUE_NUMBER
    - name: PAYLOAD
    - name: SCRIPT_PATH
    - name: SECRET_NAME
    - name: WORKING_DIR
    - name: WORKING_BRANCH_PREFIX
  stepTemplate:
    env:
      - name: GITHUB_TOKEN
        valueFrom:
          secretKeyRef:
            name: $(params.SECRET_NAME)
            key: token
      - name: ORG_NAME
        valueFrom:
          secretKeyRef:
            name: $(params.SECRET_NAME)
            key: orgName
      - name: TARGET_REPO
        value: $(params.TARGET_REPO)
      - name: SOURCE_REPO
        value: $(params.SOURCE_REPO)
      - name: ISSUE_NUMBER
        value: $(params.ISSUE_NUMBER)
      - name: PAYLOAD
        value: $(params.PAYLOAD)
      - name: SCRIPT_PATH
        value: $(params.SCRIPT_PATH)
      - name: SECRET_NAME
        value: $(params.SECRET_NAME)
      - name: WORKING_DIR
        value: $(params.WORKING_DIR)
      - name: WORKING_BRANCH_PREFIX
        value: $(params.WORKING_BRANCH_PREFIX)
  workspaces:
    - name: utility-scripts
      mountPath: /utility-scripts
    - mountPath: $(params.WORKING_DIR)
      name: shared-data
  steps:
    - name: dump-payload
      image: quay.io/operate-first/opf-toolbox
      workingDir: $(params.WORKING_DIR)
      command: ["/bin/sh", "-c", '/utility-scripts/dump-payload.sh']
    - name: apply-changes
      image: quay.io/operate-first/opf-toolbox
      workingDir: $(params.WORKING_DIR)
      command: ["/bin/sh", "-c", '/utility-scripts/setup-and-execute.sh']
    - name: create-pr
      image: ghcr.io/supportpal/github-gh-cli # TODO: Add gh cli to opf-toolbox and use that instead
      workingDir: $(params.WORKING_DIR)
      command: ['/utility-scripts/create-pr.sh']
