apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: issue-form-automation-bash
spec:
  params:
    - name: TARGET_REPO
      type: string
    - name: SECRET_NAME
      type: string
    - name: PAYLOAD
      type: string
    - name: SCRIPT_PATH
      type: string
  stepTemplate:
    env:
      - name: GITHUB_TOKEN
        valueFrom:
          secretKeyRef:
            name: $(params.SECRET_NAME)
            key: token
      - name: ORG_NAME
        valueFrom:
          secretKeyRef:
            name: $(params.SECRET_NAME)
            key: orgName
  workspaces:
    - name: utility-scripts
      mountPath: /utility-scripts
    - mountPath: /mnt/shared
      name: shared-data
  steps:
    - name: dump-payload
      image: quay.io/operate-first/opf-toolbox
      workingDir: /mnt/shared
      command: ['/utility-scripts/dump-payload.sh']
    - name: setup-git-env
      image: quay.io/operate-first/opf-toolbox
      workingDir: /mnt/shared
      command: ['/utility-scripts/setup-get-env.sh']
    - name: apply-changes
      image: quay.io/operate-first/opf-toolbox
      workingDir: /mnt/shared/$(params.TARGET_REPO)
      command: ['./$(params.SCRIPT_PATH)']
#    - name: create-pr
#      image: ghcr.io/supportpal/github-gh-cli # TODO: Add gh cli to opf-toolbox and use that instead
#      workingDir: /mnt/shared/$(params.REPO_NAME)
#      command: ['/utility-scripts/create-pr.sh']
