apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: issue-form-automation-bash
spec:
  params:
    - name: TARGET_REPO
      type: string
    - name: SECRET_NAME
      type: string
    - name: PAYLOAD
      type: string
    - name: SCRIPT_PATH
      type: string
    - name: WORKING_DIR
      type: string
  stepTemplate:
    env:
      - name: GITHUB_TOKEN
        valueFrom:
          secretKeyRef:
            name: $(params.SECRET_NAME)
            key: token
      - name: ORG_NAME
        valueFrom:
          secretKeyRef:
            name: $(params.SECRET_NAME)
            key: orgName
      - name: TARGET_REPO
        value: $(params.TARGET_REPO)
      - name: SECRET_NAME
        value: $(params.SECRET_NAME)
      - name: PAYLOAD
        value: $(params.PAYLOAD)
      - name: SCRIPT_PATH
        value: $(params.SCRIPT_PATH)
      - name: WORKING_DIR
        value: $(params.WORKING_DIR)
  workspaces:
    - name: utility-scripts
      mountPath: /utility-scripts
    - mountPath: $(params.WORKING_DIR)
      name: shared-data
  steps:
    - name: dump-payload
      image: quay.io/operate-first/opf-toolbox
      workingDir: $(params.WORKING_DIR)
      command: ["/bin/sh", "-c", '/utility-scripts/dump-payload.sh']
    - name: setup-git-env
      image: quay.io/operate-first/opf-toolbox
      workingDir: $(params.WORKING_DIR)
      command: ["/bin/sh", "-c", '/utility-scripts/setup-get-env.sh']
    - name: apply-changes
      image: quay.io/operate-first/opf-toolbox
      workingDir: $(params.WORKING_DIR)
      command: ["/bin/sh", "-c", './$(params.SCRIPT_PATH)']
#    - name: create-pr
#      image: ghcr.io/supportpal/github-gh-cli # TODO: Add gh cli to opf-toolbox and use that instead
#      workingDir: $(params.WORKING_DIR)/$(params.REPO_NAME)
#      command: ['/utility-scripts/create-pr.sh']
