apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: utility-scripts
    files:
      - scripts/create-pr.sh
      - scripts/setup-and-execute.sh
      - scripts/dump-payload.sh
      - scripts/feedback.sh
