apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: issue-form-pipeline
spec:
  workspaces:
    - name: shared-data
    - name: utility-scripts
  params:
    - name: SOURCE_REPO
      type: string
    - name: TARGET_REPO
      type: string
    - name: ISSUE_NUMBER
      type: string
    - name: PAYLOAD
      type: string
    - name: TASK_TYPE
      type: string
    - name: SCRIPT_PATH
      type: string
    - name: SECRET_NAME
      type: string
  finally:
    - name: feedback
      params:
        - name: SOURCE_REPO
          value: $(params.SOURCE_REPO)
        - name: TARGET_REPO
          value: $(params.TARGET_REPO)
        - name: ISSUE_NUMBER
          value: $(params.ISSUE_NUMBER)
        - name: SCRIPT_PATH
          value: $(params.SCRIPT_PATH)
        - name: SECRET_NAME
          value: $(params.SECRET_NAME)
        - name: aggregateTasksStatus
          value: $(tasks.status)
      taskRef:
        kind: Task
        name: feedback
      workspaces:
        - name: utility-scripts
          workspace: utility-scripts
  tasks:
    - name: issue-form-automation-bash
      params:
        - name: SOURCE_REPO
          value: $(params.SOURCE_REPO)
        - name: TARGET_REPO
          value: $(params.TARGET_REPO)
        - name: ISSUE_NUMBER
          value: $(params.ISSUE_NUMBER)
        - name: PAYLOAD
          value: $(params.PAYLOAD)
        - name: SCRIPT_PATH
          value: $(params.SCRIPT_PATH)
        - name: SECRET_NAME
          value: $(params.SECRET_NAME)
      when:
        - input: "$(params.TASK_TYPE)"
          operator: in
          values: [ "bash"]
      taskRef:
        kind: Task
        name: issue-form-automation-bash
      workspaces:
        - name: shared-data
          workspace: shared-data
        - name: utility-scripts
          workspace: utility-scripts
      timeout: "5m"
    - name: issue-form-automation-moustache
      params:
        - name: SOURCE_REPO
          value: $(params.SOURCE_REPO)
        - name: TARGET_REPO
          value: $(params.TARGET_REPO)
        - name: ISSUE_NUMBER
          value: $(params.ISSUE_NUMBER)
        - name: PAYLOAD
          value: $(params.PAYLOAD)
        - name: SCRIPT_PATH
          value: $(params.SCRIPT_PATH)
        - name: SECRET_NAME
          value: $(params.SECRET_NAME)
      when:
        - input: "$(params.TASK_TYPE)"
          operator: in
          values: [ "moustache" ]
      taskRef:
        kind: Task
        name: issue-form-automation-moustache
      workspaces:
        - name: shared-data
          workspace: shared-data
        - name: utility-scripts
          workspace: utility-scripts
      timeout: "5m"
