---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- controller
- tasks
- pipelines
- configmaps
commonLabels:
  app: robozome
configurations:
  - .transformers.yaml
images:
  - name: quay.io/operate-first/opf-toolbox
    newName: quay.io/operate-first/opf-toolbox
    newTag: v0.12.0
  - name: robozome
    newName: quay.io/operate-first/robozome
    newTag: v0.1.0
