---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- controller
- tasks
- pipelines
- configmaps
commonLabels:
  app: robozome
images:
  - name: opf-toolbox
    newName: quay.io/operate-first/opf-toolbox:v0.11.0
  - name: python
    newName: registry.access.redhat.com/ubi8/python-38
