---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: robozome
rules:
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  verbs:
  - create
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - delete
